### ISSUE TITLE
Selinux Permissive

### ISSUE THREAD

**Issue by HTC600** [penn5/android_kernel_hisilicon_hi6250#1]
Hello. May I ask you to build a core? Exclusively - **Selinux = Permissive**. The rest of the functionality is not required.

**Comment by penn5** [comment]
That's what this is

**Comment by HTC600** [comment]
@penn5 
I need a kernel only with SElinux> permissive

https://github.com/penn5/android_kernel_hisilicon_hi6250/commit/662ea51d6195424a59186d1eba3ee0ed22c129de

**Comment by HTC600** [comment]
@penn5 
My email gusfan8ka@gmail.com
My telegram http://t.me/SaWSeM

**Comment by penn5** [comment]
Ive already said, this kernel is permissive.

**Comment by HTC600** [comment]
@penn5 BootLoop
